// Landing Page Template - Serialized CraftJS data
export default {
  ROOT: {
    type: {
      resolvedName: "Frame",
    },
    isCanvas: true,
    props: {
      width: "100%",
      height: "auto",
      background: "#ffffff",
    },
    displayName: "Frame",
    custom: {},
    hidden: false,
    nodes: ["hero-section", "features-section", "cta-section"],
    linkedNodes: {},
  },
  "hero-section": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      paddingTop: "80px",
      paddingBottom: "80px",
      backgroundColor: "#f8fafc",
      width: "100%",
    },
    displayName: "Container",
    custom: {
      displayName: "Hero Section",
    },
    hidden: false,
    nodes: ["hero-content"],
    linkedNodes: {},
  },
  "hero-content": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      width: "100%",
      maxWidth: "1200px",
      margin: "0 auto",
      padding: "0 20px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      flexDirection: "row",
      flexWrap: "wrap",
    },
    displayName: "Container",
    custom: {
      displayName: "Hero Content",
    },
    hidden: false,
    nodes: ["hero-text", "hero-image"],
    linkedNodes: {},
  },
  "hero-text": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      width: "50%",
      padding: "20px",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
    },
    displayName: "Container",
    custom: {
      displayName: "Hero Text",
    },
    hidden: false,
    nodes: ["hero-heading", "hero-subheading", "hero-button"],
    linkedNodes: {},
  },
  "hero-heading": {
    type: {
      resolvedName: "Heading",
    },
    isCanvas: false,
    props: {
      text: "Create amazing websites with our platform",
      level: 1,
      fontSize: "48px",
      fontWeight: "700",
      color: "#0f172a",
      marginBottom: "16px",
    },
    displayName: "Heading",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "hero-subheading": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Build beautiful, responsive websites without writing a single line of code. Our intuitive drag-and-drop editor makes it easy for anyone to create professional websites.",
      fontSize: "18px",
      color: "#64748b",
      marginBottom: "32px",
      lineHeight: "1.6",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "hero-button": {
    type: {
      resolvedName: "CraftButton",
    },
    isCanvas: false,
    props: {
      text: "Get Started",
      variant: "default",
      size: "lg",
      backgroundColor: "#3b82f6",
      color: "white",
      fontSize: "16px",
      fontWeight: "500",
      paddingLeft: "24px",
      paddingRight: "24px",
      borderRadius: "8px",
    },
    displayName: "CraftButton",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "hero-image": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: false,
    props: {
      width: "50%",
      padding: "20px",
      backgroundImage: "url('/hero-image.jpg')",
      backgroundSize: "cover",
      backgroundPosition: "center",
      minHeight: "400px",
      borderRadius: "16px",
    },
    displayName: "Container",
    custom: {
      displayName: "Hero Image",
    },
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "features-section": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      paddingTop: "80px",
      paddingBottom: "80px",
      backgroundColor: "#ffffff",
      width: "100%",
    },
    displayName: "Container",
    custom: {
      displayName: "Features Section",
    },
    hidden: false,
    nodes: ["features-container"],
    linkedNodes: {},
  },
  "features-container": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      width: "100%",
      maxWidth: "1200px",
      margin: "0 auto",
      padding: "0 20px",
    },
    displayName: "Container",
    custom: {
      displayName: "Features Container",
    },
    hidden: false,
    nodes: ["features-heading", "features-grid"],
    linkedNodes: {},
  },
  "features-heading": {
    type: {
      resolvedName: "Heading",
    },
    isCanvas: false,
    props: {
      text: "Features",
      level: 2,
      fontSize: "36px",
      fontWeight: "700",
      color: "#0f172a",
      marginBottom: "48px",
      textAlign: "center",
    },
    displayName: "Heading",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "features-grid": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: "24px",
    },
    displayName: "Container",
    custom: {
      displayName: "Features Grid",
    },
    hidden: false,
    nodes: ["feature-1", "feature-2", "feature-3"],
    linkedNodes: {},
  },
  "feature-1": {
    type: {
      resolvedName: "CraftCard",
    },
    isCanvas: true,
    props: {
      title: "Easy to Use",
      padding: "24px",
      borderRadius: "12px",
      boxShadow:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    },
    displayName: "CraftCard",
    custom: {},
    hidden: false,
    nodes: ["feature-1-description"],
    linkedNodes: {},
  },
  "feature-1-description": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Our intuitive drag-and-drop editor makes website building accessible to everyone, regardless of technical skills.",
      color: "#64748b",
      lineHeight: "1.6",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-2": {
    type: {
      resolvedName: "CraftCard",
    },
    isCanvas: true,
    props: {
      title: "Responsive Design",
      padding: "24px",
      borderRadius: "12px",
      boxShadow:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    },
    displayName: "CraftCard",
    custom: {},
    hidden: false,
    nodes: ["feature-2-description"],
    linkedNodes: {},
  },
  "feature-2-description": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "All websites created with our platform are fully responsive and look great on any device, from desktop to mobile.",
      color: "#64748b",
      lineHeight: "1.6",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "feature-3": {
    type: {
      resolvedName: "CraftCard",
    },
    isCanvas: true,
    props: {
      title: "Customizable Templates",
      padding: "24px",
      borderRadius: "12px",
      boxShadow:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    },
    displayName: "CraftCard",
    custom: {},
    hidden: false,
    nodes: ["feature-3-description"],
    linkedNodes: {},
  },
  "feature-3-description": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Choose from a wide range of professionally designed templates and customize them to match your brand identity.",
      color: "#64748b",
      lineHeight: "1.6",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cta-section": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      paddingTop: "80px",
      paddingBottom: "80px",
      backgroundColor: "#3b82f6",
      width: "100%",
      color: "white",
    },
    displayName: "Container",
    custom: {
      displayName: "CTA Section",
    },
    hidden: false,
    nodes: ["cta-container"],
    linkedNodes: {},
  },
  "cta-container": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      width: "100%",
      maxWidth: "800px",
      margin: "0 auto",
      padding: "0 20px",
      textAlign: "center",
    },
    displayName: "Container",
    custom: {
      displayName: "CTA Container",
    },
    hidden: false,
    nodes: ["cta-heading", "cta-text", "cta-button"],
    linkedNodes: {},
  },
  "cta-heading": {
    type: {
      resolvedName: "Heading",
    },
    isCanvas: false,
    props: {
      text: "Ready to build your website?",
      level: 2,
      fontSize: "36px",
      fontWeight: "700",
      color: "white",
      marginBottom: "16px",
    },
    displayName: "Heading",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cta-text": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Start your free trial today and discover how easy it is to create a stunning website with our platform.",
      fontSize: "18px",
      color: "rgba(255, 255, 255, 0.9)",
      marginBottom: "32px",
      lineHeight: "1.6",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "cta-button": {
    type: {
      resolvedName: "CraftButton",
    },
    isCanvas: false,
    props: {
      text: "Start Free Trial",
      variant: "outline",
      size: "lg",
      backgroundColor: "transparent",
      color: "white",
      fontSize: "16px",
      fontWeight: "500",
      paddingLeft: "24px",
      paddingRight: "24px",
      borderRadius: "8px",
      border: "2px solid white",
    },
    displayName: "CraftButton",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};
