export default {
  ROOT: {
    type: {
      resolvedName: "Frame",
    },
    isCanvas: true,
    props: {
      width: "100%",
      height: "auto",
      background: "#ffffff",
    },
    displayName: "Frame",
    custom: {},
    hidden: false,
    nodes: [
      "header-section",
      "about-section",
      "portfolio-section",
      "contact-section",
    ],
    linkedNodes: {},
  },
  "header-section": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      paddingTop: "120px",
      paddingBottom: "120px",
      backgroundColor: "#1e293b",
      width: "100%",
      color: "white",
      textAlign: "center",
    },
    displayName: "Container",
    custom: {
      displayName: "Header Section",
    },
    hidden: false,
    nodes: ["header-content"],
    linkedNodes: {},
  },
  "header-content": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      width: "100%",
      maxWidth: "800px",
      margin: "0 auto",
      padding: "0 20px",
    },
    displayName: "Container",
    custom: {
      displayName: "Header Content",
    },
    hidden: false,
    nodes: ["profile-image", "name-heading", "job-title", "intro-text"],
    linkedNodes: {},
  },
  "profile-image": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: false,
    props: {
      width: "150px",
      height: "150px",
      borderRadius: "50%",
      backgroundColor: "#94a3b8",
      margin: "0 auto 24px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    displayName: "Container",
    custom: {
      displayName: "Profile Image",
    },
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "name-heading": {
    type: {
      resolvedName: "Heading",
    },
    isCanvas: false,
    props: {
      text: "Jane Doe",
      level: 1,
      fontSize: "48px",
      fontWeight: "700",
      color: "white",
      marginBottom: "16px",
    },
    displayName: "Heading",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "job-title": {
    type: {
      resolvedName: "Heading",
    },
    isCanvas: false,
    props: {
      text: "UI/UX Designer & Developer",
      level: 2,
      fontSize: "24px",
      fontWeight: "500",
      color: "#94a3b8",
      marginBottom: "32px",
    },
    displayName: "Heading",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "intro-text": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "I design and build beautiful digital experiences that help businesses connect with their customers. With 5+ years of experience, I specialize in creating user-friendly interfaces and responsive websites.",
      fontSize: "18px",
      color: "#cbd5e1",
      lineHeight: "1.6",
      maxWidth: "700px",
      margin: "0 auto",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "about-section": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      paddingTop: "80px",
      paddingBottom: "80px",
      backgroundColor: "#ffffff",
      width: "100%",
    },
    displayName: "Container",
    custom: {
      displayName: "About Section",
    },
    hidden: false,
    nodes: ["about-container"],
    linkedNodes: {},
  },
  "about-container": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      width: "100%",
      maxWidth: "1000px",
      margin: "0 auto",
      padding: "0 20px",
    },
    displayName: "Container",
    custom: {
      displayName: "About Container",
    },
    hidden: false,
    nodes: ["about-heading", "about-content"],
    linkedNodes: {},
  },
  "about-heading": {
    type: {
      resolvedName: "Heading",
    },
    isCanvas: false,
    props: {
      text: "About Me",
      level: 2,
      fontSize: "36px",
      fontWeight: "700",
      color: "#0f172a",
      marginBottom: "48px",
      textAlign: "center",
    },
    displayName: "Heading",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "about-content": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      display: "flex",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: "40px",
    },
    displayName: "Container",
    custom: {
      displayName: "About Content",
    },
    hidden: false,
    nodes: ["about-text", "skills-container"],
    linkedNodes: {},
  },
  "about-text": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      flex: "1",
      minWidth: "300px",
    },
    displayName: "Container",
    custom: {
      displayName: "About Text",
    },
    hidden: false,
    nodes: ["about-paragraph-1", "about-paragraph-2"],
    linkedNodes: {},
  },
  "about-paragraph-1": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "I'm a UI/UX designer and frontend developer with a passion for creating intuitive, accessible, and beautiful digital experiences. I believe that good design should be both aesthetically pleasing and highly functional.",
      fontSize: "16px",
      color: "#334155",
      lineHeight: "1.6",
      marginBottom: "16px",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "about-paragraph-2": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "My approach combines user-centered design principles with clean, efficient code to deliver projects that exceed client expectations. I'm constantly learning and exploring new technologies to stay at the forefront of this rapidly evolving field.",
      fontSize: "16px",
      color: "#334155",
      lineHeight: "1.6",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "skills-container": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      flex: "1",
      minWidth: "300px",
    },
    displayName: "Container",
    custom: {
      displayName: "Skills Container",
    },
    hidden: false,
    nodes: ["skills-heading", "skills-grid"],
    linkedNodes: {},
  },
  "skills-heading": {
    type: {
      resolvedName: "Heading",
    },
    isCanvas: false,
    props: {
      text: "Skills & Expertise",
      level: 3,
      fontSize: "24px",
      fontWeight: "600",
      color: "#0f172a",
      marginBottom: "24px",
    },
    displayName: "Heading",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "skills-grid": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      display: "grid",
      gridTemplateColumns: "repeat(2, 1fr)",
      gap: "16px",
    },
    displayName: "Container",
    custom: {
      displayName: "Skills Grid",
    },
    hidden: false,
    nodes: ["skill-1", "skill-2", "skill-3", "skill-4", "skill-5", "skill-6"],
    linkedNodes: {},
  },
  "skill-1": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "UI/UX Design",
      fontSize: "16px",
      color: "#334155",
      fontWeight: "500",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "skill-2": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "React.js",
      fontSize: "16px",
      color: "#334155",
      fontWeight: "500",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "skill-3": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "HTML & CSS",
      fontSize: "16px",
      color: "#334155",
      fontWeight: "500",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "skill-4": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Responsive Design",
      fontSize: "16px",
      color: "#334155",
      fontWeight: "500",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "skill-5": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Figma & Sketch",
      fontSize: "16px",
      color: "#334155",
      fontWeight: "500",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "skill-6": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "TypeScript",
      fontSize: "16px",
      color: "#334155",
      fontWeight: "500",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "portfolio-section": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      paddingTop: "80px",
      paddingBottom: "80px",
      backgroundColor: "#f8fafc",
      width: "100%",
    },
    displayName: "Container",
    custom: {
      displayName: "Portfolio Section",
    },
    hidden: false,
    nodes: ["portfolio-container"],
    linkedNodes: {},
  },
  "portfolio-container": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      width: "100%",
      maxWidth: "1200px",
      margin: "0 auto",
      padding: "0 20px",
    },
    displayName: "Container",
    custom: {
      displayName: "Portfolio Container",
    },
    hidden: false,
    nodes: ["portfolio-heading", "portfolio-grid"],
    linkedNodes: {},
  },
  "portfolio-heading": {
    type: {
      resolvedName: "Heading",
    },
    isCanvas: false,
    props: {
      text: "My Work",
      level: 2,
      fontSize: "36px",
      fontWeight: "700",
      color: "#0f172a",
      marginBottom: "48px",
      textAlign: "center",
    },
    displayName: "Heading",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "portfolio-grid": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))",
      gap: "32px",
    },
    displayName: "Container",
    custom: {
      displayName: "Portfolio Grid",
    },
    hidden: false,
    nodes: ["project-1", "project-2", "project-3"],
    linkedNodes: {},
  },
  "project-1": {
    type: {
      resolvedName: "CraftCard",
    },
    isCanvas: true,
    props: {
      title: "E-commerce Website",
      padding: "0",
      borderRadius: "12px",
      overflow: "hidden",
      boxShadow:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    },
    displayName: "CraftCard",
    custom: {},
    hidden: false,
    nodes: ["project-1-content"],
    linkedNodes: {},
  },
  "project-1-content": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      padding: "20px",
    },
    displayName: "Container",
    custom: {
      displayName: "Project 1 Content",
    },
    hidden: false,
    nodes: ["project-1-image", "project-1-description", "project-1-button"],
    linkedNodes: {},
  },
  "project-1-image": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: false,
    props: {
      width: "100%",
      height: "200px",
      backgroundColor: "#94a3b8",
      marginBottom: "16px",
      borderRadius: "8px",
    },
    displayName: "Container",
    custom: {
      displayName: "Project 1 Image",
    },
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "project-1-description": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Designed and developed a responsive e-commerce platform with user-friendly navigation and checkout process.",
      fontSize: "16px",
      color: "#334155",
      lineHeight: "1.6",
      marginBottom: "16px",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "project-1-button": {
    type: {
      resolvedName: "CraftButton",
    },
    isCanvas: false,
    props: {
      text: "View Project",
      variant: "default",
      size: "default",
      width: "100%",
    },
    displayName: "CraftButton",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "project-2": {
    type: {
      resolvedName: "CraftCard",
    },
    isCanvas: true,
    props: {
      title: "Mobile App UI",
      padding: "0",
      borderRadius: "12px",
      overflow: "hidden",
      boxShadow:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    },
    displayName: "CraftCard",
    custom: {},
    hidden: false,
    nodes: ["project-2-content"],
    linkedNodes: {},
  },
  "project-2-content": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      padding: "20px",
    },
    displayName: "Container",
    custom: {
      displayName: "Project 2 Content",
    },
    hidden: false,
    nodes: ["project-2-image", "project-2-description", "project-2-button"],
    linkedNodes: {},
  },
  "project-2-image": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: false,
    props: {
      width: "100%",
      height: "200px",
      backgroundColor: "#94a3b8",
      marginBottom: "16px",
      borderRadius: "8px",
    },
    displayName: "Container",
    custom: {
      displayName: "Project 2 Image",
    },
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "project-2-description": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Created a modern UI design for a fitness tracking mobile application, focusing on user experience and visual aesthetics.",
      fontSize: "16px",
      color: "#334155",
      lineHeight: "1.6",
      marginBottom: "16px",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "project-2-button": {
    type: {
      resolvedName: "CraftButton",
    },
    isCanvas: false,
    props: {
      text: "View Project",
      variant: "default",
      size: "default",
      width: "100%",
    },
    displayName: "CraftButton",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "project-3": {
    type: {
      resolvedName: "CraftCard",
    },
    isCanvas: true,
    props: {
      title: "Corporate Website",
      padding: "0",
      borderRadius: "12px",
      overflow: "hidden",
      boxShadow:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    },
    displayName: "CraftCard",
    custom: {},
    hidden: false,
    nodes: ["project-3-content"],
    linkedNodes: {},
  },
  "project-3-content": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      padding: "20px",
    },
    displayName: "Container",
    custom: {
      displayName: "Project 3 Content",
    },
    hidden: false,
    nodes: ["project-3-image", "project-3-description", "project-3-button"],
    linkedNodes: {},
  },
  "project-3-image": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: false,
    props: {
      width: "100%",
      height: "200px",
      backgroundColor: "#94a3b8",
      marginBottom: "16px",
      borderRadius: "8px",
    },
    displayName: "Container",
    custom: {
      displayName: "Project 3 Image",
    },
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "project-3-description": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Redesigned a corporate website to improve brand identity and user engagement, resulting in a 40% increase in conversion rate.",
      fontSize: "16px",
      color: "#334155",
      lineHeight: "1.6",
      marginBottom: "16px",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "project-3-button": {
    type: {
      resolvedName: "CraftButton",
    },
    isCanvas: false,
    props: {
      text: "View Project",
      variant: "default",
      size: "default",
      width: "100%",
    },
    displayName: "CraftButton",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "contact-section": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      paddingTop: "80px",
      paddingBottom: "80px",
      backgroundColor: "#1e293b",
      width: "100%",
      color: "white",
    },
    displayName: "Container",
    custom: {
      displayName: "Contact Section",
    },
    hidden: false,
    nodes: ["contact-container"],
    linkedNodes: {},
  },
  "contact-container": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      width: "100%",
      maxWidth: "800px",
      margin: "0 auto",
      padding: "0 20px",
      textAlign: "center",
    },
    displayName: "Container",
    custom: {
      displayName: "Contact Container",
    },
    hidden: false,
    nodes: ["contact-heading", "contact-text", "contact-form"],
    linkedNodes: {},
  },
  "contact-heading": {
    type: {
      resolvedName: "Heading",
    },
    isCanvas: false,
    props: {
      text: "Get In Touch",
      level: 2,
      fontSize: "36px",
      fontWeight: "700",
      color: "white",
      marginBottom: "16px",
    },
    displayName: "Heading",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "contact-text": {
    type: {
      resolvedName: "Paragraph",
    },
    isCanvas: false,
    props: {
      text: "Interested in working together? Fill out the form below and I'll get back to you as soon as possible.",
      fontSize: "18px",
      color: "#cbd5e1",
      lineHeight: "1.6",
      marginBottom: "32px",
    },
    displayName: "Paragraph",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "contact-form": {
    type: {
      resolvedName: "Container",
    },
    isCanvas: true,
    props: {
      width: "100%",
      maxWidth: "500px",
      margin: "0 auto",
      textAlign: "left",
    },
    displayName: "Container",
    custom: {
      displayName: "Contact Form",
    },
    hidden: false,
    nodes: ["form-name", "form-email", "form-message", "form-submit"],
    linkedNodes: {},
  },
  "form-name": {
    type: {
      resolvedName: "CraftInput",
    },
    isCanvas: false,
    props: {
      placeholder: "Your Name",
      marginBottom: "16px",
      width: "100%",
      backgroundColor: "rgba(255,255,255,0.1)",
      color: "white",
      border: "none",
      padding: "12px 16px",
      borderRadius: "8px",
    },
    displayName: "CraftInput",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "form-email": {
    type: {
      resolvedName: "CraftInput",
    },
    isCanvas: false,
    props: {
      placeholder: "Your Email",
      marginBottom: "16px",
      width: "100%",
      backgroundColor: "rgba(255,255,255,0.1)",
      color: "white",
      border: "none",
      padding: "12px 16px",
      borderRadius: "8px",
    },
    displayName: "CraftInput",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "form-message": {
    type: {
      resolvedName: "CraftTextarea",
    },
    isCanvas: false,
    props: {
      placeholder: "Your Message",
      marginBottom: "24px",
      width: "100%",
      height: "150px",
      backgroundColor: "rgba(255,255,255,0.1)",
      color: "white",
      border: "none",
      padding: "12px 16px",
      borderRadius: "8px",
    },
    displayName: "CraftTextarea",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "form-submit": {
    type: {
      resolvedName: "CraftButton",
    },
    isCanvas: false,
    props: {
      text: "Send Message",
      variant: "default",
      size: "lg",
      width: "100%",
      backgroundColor: "#3b82f6",
      color: "white",
      borderRadius: "8px",
    },
    displayName: "CraftButton",
    custom: {},
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};
